export const translateJsonMap = {
  'rcp-fe-ember-libs': [
    'trans-icon-rarity',
    'trans-loadouts-modal',
    'trans-loot-table',
    'trans-patcher-and-play-button',
  ],
  'rcp-fe-lol-champ-select': ['trans'],
  'rcp-fe-lol-champion-details': ['trans'],
  'rcp-fe-lol-clash': ['trans'],
  'rcp-fe-lol-collections': [
    'trans',
    'trans-perks',
    'trans-item-sets',
    'trans-emote-panel',
  ],
  'rcp-fe-lol-esports-spectate': ['trans'],
  'rcp-fe-lol-event-hub': ['trans'],
  'rcp-fe-lol-highlights': ['trans'],
  'rcp-fe-lol-honor': ['trans'],
  'rcp-fe-lol-l10n': ['trans'],
  'rcp-fe-lol-leagues': ['trans'],
  'rcp-fe-lol-loot': ['trans'],
  'rcp-fe-lol-match-history': ['trans'],
  'rcp-fe-lol-navigation': [
    'trans',
    'trans-app-controls',
    'trans-activity-center',
    'trans-champion-mastery-notifications',
    'trans-email-verification',
    'trans-game-in-progress',
    'trans-loading-screen',
    'trans-npe-first-touch',
  ],
  'rcp-fe-lol-new-player-experience': ['trans'],
  'rcp-fe-lol-objectives': ['trans'],
  'rcp-fe-lol-parties': ['trans'],
  'rcp-fe-lol-paw': ['trans'],
  'rcp-fe-lol-pft': ['trans'],
  'rcp-fe-lol-postgame': ['trans'],
  'rcp-fe-lol-premade-voice': ['trans'],
  'rcp-fe-lol-profiles': ['trans'],
  'rcp-fe-lol-settings': ['trans', 'trans-legal-statements'],
  'rcp-fe-lol-shared-components': [
    'trans-account-verification',
    'trans-challenges',
    'trans-champion-mastery',
    'trans-currency-container',
    'trans-digital-goods-disclaimer',
    'trans-eternals',
    'trans-league-tier-names',
    'trans-regalia',
    'trans-replays',
    'trans-report-modal',
    'trans-shoppefront',
    'trans',
  ],
  'rcp-fe-lol-skins-picker': ['trans'],
  'rcp-fe-lol-social': ['trans', 'trans-player-behavior'],
  'rcp-fe-lol-store': ['trans'],
  'rcp-fe-lol-tft-team-planner': ['trans'],
  'rcp-fe-lol-tft': [
    'trans',
    'trans-troves',
    'trans-skill-tree',
    'trans-rotational-shop',
  ],
  'rcp-fe-lol-yourshop': ['trans'],
} as const;

export type TranslatePathKeys = keyof typeof translateJsonMap;
